spring:
  datasource:
    url: jdbc:mariadb://portfolio-maria-db.cbt4fdfoovm1.us-east-2.rds.amazonaws.com:3306/portfolio
    username: root
    password: pw192837
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  security:
    securityKey: ${random.value}
  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: jook1356 # 3
    password: ljdfolzjvzzamzlg # 4
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7
