logging:
  level:
    root: DEBUG
spring:
  datasource:
    password: 1356
    url: jdbc:mariadb://localhost:3306/cardb
    username: root
  jpa:
    generate-ddl: true
#    hibernate:
#      ddl-auto: create-drop
    show-sql: true
  data:
    rest:
      base-path: /api
server:
  port: 8081