logging:
  level:
    root: DEBUG
spring:
  datasource:
    password: pw192837
    url: jdbc:mariadb://portfolio-maria-db.cbt4fdfoovm1.us-east-2.rds.amazonaws.com:3306/portfolio
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
#    hibernate:
#      ddl-auto: create-drop
    show-sql: true
#  data:
#    rest:
#      base-path: /api
  security:
    securityKey: ${random.value}

server:
  port: 8081
