version: '3'
services:
  api-module:
    build: ./api-module
    image: back/api-module
    ports:
      - "8081:443"
    environment:
      TZ: "Asia/Seoul"
    logging:
      driver: syslog
      options:
        tag: back